server.port=3030

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ContactManagementDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=cms_user
spring.datasource.password=Cms@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
