spring.application.name=contact-management-backend

server.port=3030

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.com.saif.contactmanagement=DEBUG