sonar.projectKey=cohort-9-java-14637-saif
sonar.projectName=cohort-9-java-14637-saif-fullstack
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=backend/contact-management-backend/src/main/java,frontend/src
sonar.tests=backend/contact-management-backend/src/test/java

# Language specific settings
sonar.java.binaries=backend/contact-management-backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/contact-management-backend/target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/node_modules/**,**/target/**,**/.mvn/**,**/build/**,**/dist/**
